USE GESTION_STOCK;
GO
CREATE TRIGGER trg_ValidarPrecio_Producto
ON Productos
AFTER INSERT
AS
BEGIN
    IF EXISTS (SELECT 1 FROM inserted WHERE PrecioUnitario < 0)
    BEGIN
        RAISERROR('NO SE PUEDE AGREGAR PRECIOS NEGATIVOS A LOS PRODUCTOS', 16, 1);
        ROLLBACK TRANSACTION;
        RETURN;
    END
END;
GO
CREATE TRIGGER trg_StockMinimo_Producto
ON Productos
AFTER UPDATE
AS 
BEGIN
IF EXISTS (SELECT * FROM inserted WHERE Stock<StockMinimo)
BEGIN
 RAISERROR('EL STOCK ES MENOS QUE EL MINIMO PERMITIDO, NO SE PUEDE DESCONTAR ESA CANTIDAD', 16, 1);
 ROLLBACK TRANSACTION
 RETURN;
END
END
GO



